hana/hana/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from graphene_django.views import GraphQLView



from . import views


schema_view = get_schema_view(
    openapi.Info(
        title="HANA API",
        default_version='v0.1b',
        description="HANA API for monitoring and managing swarms and nodes",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('swarman/', include(('swarman.urls', 'swarman'), namespace='swarman')),
    path('docs/api', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("graphql",csrf_exempt(GraphQLView.as_view(graphiql=True)), name="schema-graphql"),
]

hana/swarman/api/urls.py
from django.urls import (
    path,
    include,
)


urlpatterns = [
    path('', include('swarman.api.v1_0.urls')),
    
    # path('v1.0/', include('swarman.api.v1_0.urls')),
]

hana/swarman/api/v1_0/urls.py
from django.urls import path

from .api_views import (
    SwarmViewSet,
    NodeList,
    get_existing_swarm_nodes,
    add_existing_swarm_nodes,
    leave_swarm,
    update_node_availability,
    promote_node,
    demote_node,
    node_utilization,
    sync_node_data,
    service_scale,
)


swarm_list = SwarmViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

swarm_detail = SwarmViewSet.as_view({
    'get': 'retrieve',
})


urlpatterns = [
    path('swarms/', swarm_list, name='api-swarm-list'),
    path('swarms/<int:pk>', swarm_detail, name='api-swarm-detail'),
    path('swarms/<int:swarm_id>/nodes', NodeList.as_view(),
         name='api-node-list'),
    path('swarms/existing_swarm_nodes', get_existing_swarm_nodes,
         name="api-existing-swarm-nodes"),
    path('swarms/add_existing_swarm_nodes',
         add_existing_swarm_nodes, name="api-add-swarm-nodes"),

    path('nodes/<int:node_id>/leave', leave_swarm, name='api-leave-swarm'),
    path('nodes/<int:node_id>/promote', promote_node, name='api-node-promote'),
    path('nodes/<int:node_id>/demote', demote_node, name='api-node-demote'),
    path('nodes/<int:node_id>/utilization',
         node_utilization, name='api-node-utilization'),
    path('nodes/<int:node_id>/update', update_node_availability,
         name='api-update-node'),
    path('nodes/<int:node_id>/sync', sync_node_data, name='api-sync-node'),

    path('service/scale', service_scale, name='api-service-scale'),
]

hana/swarman/urls.py
from django.urls import (
    path,
    include,
)

from . import views


urlpatterns = [
    path('dashboard/<int:swarm_id>', views.swarm_dashboard,
         name='swarm-dashboard'),
    path('nodes/<str:node_id>', views.node_detail, name='node-detail'),
    path('new_swarm/', views.AddSwarm.as_view(), name='new-swarm'),
    path('create_swarm/', views.create_swarm, name='create-swarm'),
    path('swarm/<int:swarm_id>/service', views.service_detail, 
        name='service-detail'),
    path('api/', include('swarman.api.urls')),
    

]

hana/swarman/views.py
from django.shortcuts import (
    render,
    get_object_or_404
)
from django.http import JsonResponse
from django.views import View
from django.utils.html import format_html

import requests
import json
import docker

from .models import (
    Swarm,
    Node,
)


SWARM_MANAGER_URL = 'http://192.168.1.200:2375'

# Create your views here.


def swarm_dashboard(request, swarm_id):
    """
    Display information about a swarm. Includes node and service status
    """
    swarm = get_object_or_404(Swarm, id=swarm_id)
    nodes = swarm.nodes.order_by('hostname')

    services = []
    service_list = swarm.get_services()

    if "Error" not in service_list:
        for service in swarm.get_services():
            service_info = {
                'name': service['Spec']['Name'],
                'ID': service['ID'],
                'image': service['Spec']['TaskTemplate']['ContainerSpec']['Image'].split('@')[0],
                'replicas': service['Spec']['Mode']['Replicated']['Replicas'],
                'desired_tasks': service['ServiceStatus']['DesiredTasks'],
                'target_port': service['Endpoint']['Ports'][0]['TargetPort'],
                'published_port': service['Endpoint']['Ports'][0]['PublishedPort'],
            }
            tasks = swarm.get_service_tasks(service['ID'])
            service_info['replicas'] = 0
            for task in tasks:
                if task['Status']['State'] == "running":
                    service_info['replicas'] += 1

            services.append(service_info)

    else:
        services.append('ERROR')

    context = {
        "swarm": swarm,
        "nodes": nodes,
        "services": services,
    }
    # print(services)
    return render(request, 'swarman/swarm_dashboard.html', context)


def node_detail(request, node_id):
    """
    Displays Node Specific Details
    """
    # Get Node Object
    node = get_object_or_404(Node, id=node_id)

    # Get Container List
    try:
        client = docker.DockerClient(
            base_url=f'tcp://{node.ip_address}:{node.api_port}')
        containers = []
        for container in client.containers.list():
            containers.append(container.attrs)

    except:
        containers = [{"error": "Error retrieving containers"}]

    context = {
        'node': node,
        'containers': containers,
    }

    return render(request, 'swarman/node_detail.html', context)


def create_swarm(request):
    '''Creates a New Swarm in Swarm Model'''

    swarm_name = request.GET.get('name', None)

    if swarm_name:
        # Check to see if swarm_name is currently in use
        s = Swarm.objects.filter(swarm_name=swarm_name).first()

        if not s:
            # If not in use, create a new swarm
            print(f"No Swarm with name {swarm_name} Found, creating now")
            try:
                Swarm.objects.create(swarm_name=swarm_name)
                return JsonResponse({'success': f'{swarm_name} created successfully'})
            except:
                return JsonResponse({'error': 'An error has occured'})

        else:
            # If in use, send error Code
            return JsonResponse({'error': f'{swarm_name} already in use'})
    else:
        return JsonResponse({'error': 'Swarm Name cannot be blank'})


class AddSwarm(View):
    '''
    Class View for adding new swarms to swarman
    '''

    template_name = 'swarman/new_swarm.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        # If request contains
        pass


def service_detail(request, swarm_id):

    if request.method == "GET":

        service_id = request.GET.get('service', None)
        context = {
            'swarm_id' : swarm_id,
        }
        swarm = get_object_or_404(Swarm, id=swarm_id)
        if service_id:
            service = swarm.get_service_data(service_id)
            tasks = swarm.get_service_tasks(service_id)
            context['running_tasks'] = 0
            for task in tasks:
                if task['Status']['State'] == "running":
                    context['running_tasks'] += 1
            
            context['service_name'] = service['Spec']['Name']
            context['service_id'] = service['ID']
            context['replicas'] = service['Spec']['Mode']['Replicated']['Replicas']
            context['image'] = service['Spec']['TaskTemplate']['ContainerSpec']['Image'].split('@')[0]
            context['published_port'] = service['Spec']['EndpointSpec']['Ports'][0]['PublishedPort']
            context['target_port'] = service['Spec']['EndpointSpec']['Ports'][0]['TargetPort']
            # Calculate Service Status
            if context['running_tasks'] == 0 and context['replicas'] == 0:
                context['service_status'] = 'Paused'
                context['service_status_display'] = format_html('<strong><span class="pause">{}</span></strong>',
                                                        'Paused')  
            elif 0 < context['running_tasks'] < context['replicas']:
                context['service_status'] = 'Degraded'
                context['service_status_display'] = format_html('<strong><span class="degraded">{}</span></strong>',
                                                        'Degraded')
            elif 0 == context['running_tasks'] < context['replicas']:
                context['service_status'] = 'Error'
                context['service_status_display'] = format_html('<strong><span class="error">{}</span></strong>',
                                                        'Error')
            else:
                context['service_status'] = 'Running'
                context['service_status_display'] = format_html('<strong><span class="running">{}</span></strong>',
                                                        'Running')
            
            
        else:
            context['error'] = 'Service ID is a required URL parameter'

        return render(request, 'swarman/service_detail.html', context)

hana/swarman/templates/swarman/new_swarm.html
{% extends 'base.html' %}


{% block templateStatics %}
    {% load static %}
    <script src="{% static 'swarman/new_swarm.js' %}"></script>
{% endblock %}


{% block content %}
<div class="container">
    <h4>Setup New Swarm</h4>
    <div class="container text-center" id="swarm_setup">
       
            <button type="button" class="btn btn-primary" style="margin: 10px;" onclick="new_swarm()" disabled>Create New Swarm</button>
            <button type="button" class="btn btn-primary" style="margin: 10px;" onclick="existing_swarm()">Add Existing Swarm</button>
            
        </div>
    </div>
</div>

{% endblock %}

hana/swarman/templates/swarman/node_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row" style="padding-bottom: 20px">
        <div class='col' style="padding-top: 10px;">
        <a class="btn btn-outline-primary" href="{% url 'swarman:swarm-dashboard' node.swarm.id %}">Back to Swarm</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="row">
                <div class="col">
                    <h5>{{ node.hostname|title }} Details</h5>
                        <p>
                             <!-- Live Data - Get from JS -->
                            <span class="{{ node.get_status }}">{{ node.get_status|title }}</span> - <span class="{{ node.get_availability }}">{{ node.get_availability|title }}</span>
                        </p>
                        <p>
                            <strong>Utilization</strong><br>
                            <!-- Live Data - Get from JS -->
                            <span id="node_utilization">
                                CPU: --%<br>
                                Memory: --%
                            </span>
                        </p>
                        <p>
                            <strong>ID:</strong> {{ node.node_id }} <br>
                            <strong>Role:</strong> {{ node.role }} <br>
                            <strong>IP Address:</strong> {{ node.ip_address }} <br>
                            <strong>Architecture:</strong> {{ node.node_architecture }} <br>
                            <strong>OS:</strong> {{ node.os }} <br>
                            <strong>CPU Count:</strong> {{ node.cpu_count }} <br>
                            <strong>Total Memory:</strong> {{ node.total_memory|floatformat:3 }}GB <br>
                            <strong>Docker Engine Version:</strong> {{ node.docker_engine }}
                        </p>
                        
                </div>
            </div>
        
            <div class="row">
                <div class="col">
                <h5>Containers</h5>
                {% if containers %}
                    {% for container in containers %}
                        {% if container.error %}
                                {{ container.error }}
                        {% else %}
                                <div class="card" style="margin-bottom: 10px;">
                                    <div class="card-body">
                                        <h6 class="card-title">{{ container.Name }}</h6>
                                        <p class="card-text">
                                            {{ container.State.Status|title }}<br>
                                            <strong>Image:</strong> {{ container.Config.Image }}<br>
                                            <strong>CPU Utilization:</strong> <span id="{{ container.Name }}-cpu">--%</span><br>
                                            <strong>Memory Utilization:</strong> <span id="{{ container.Name }}-memory">--%</span><br>
                                        </p>
                                    </div>
                                </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                No Containers Running on {{ node.hostname }}
                {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-3 text-center">
            <h5>Node Actions</h5>
                <div class="row" style="padding-top: 10px;">
                    <button type="button" class="btn btn-secondary" onclick="sync_node()">Sync Node Entry</button>
                </div>
                <div class="row" style="padding-top: 10px; padding-bottom: 20px;">
                {% if node.role == "Worker" %}
                    <button type="button" class="btn btn-secondary" onclick="promote_node()">Promote Node</button>
                {% else %}
                    <button type="button" class="btn btn-secondary" onclick="demote_node()">Demote Node</button>
                {% endif %}
                </div>
                <!-- Live Data - Get from JS The Availability Buttons should be populated by Javascript -->
                {% if node.get_availability == "Error" %}
                    Can not get Node Availability
                {% else %}
                    {% if node.get_availability != "active" %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-success" onclick="update_availability('active')">Activate Node</button>
                    </div>
                    {% endif %}
                    {% if node.get_availability != "pause" %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-warning" onclick="update_availability('pause')">Pause Node</button>
                    </div>
                    {% endif %}
                    {% if node.get_availability != "drain" %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-warning" onclick="update_availability('drain')">Drain Node</button>
                    </div>
                    {% endif %}
                {% endif %}
                <div class="row" style="padding-top: 30px;">
                    <button type="button" class="btn btn-danger" disabled>Leave Swarm</button>
                </div>
            </ul>
        </div>
    </div>
</div>

<script language='javascript'>
function get_container_utilization() {
    // This function will hit an endpoint that pulls from all the containers
    // And pulls the information for each container then sums the totals
    // And populates the Nodes total usage
    
    //Poll an API Endpoint
    $.get("/swarman/api/nodes/{{ node.id }}/utilization", function(data, status) {
        
        var total_cpu_utilization = 0
        var total_memory_utilization = 0

        for(var i=0; i < data.length; i++) {
            total_cpu_utilization += data[i].cpu
            total_memory_utilization += data[i].memory

            cpu = document.getElementById(`${data[i].name}-cpu`)
            mem = document.getElementById(`${data[i].name}-memory`)

            cpu.innerHTML = `${data[i].cpu}%`
            mem.innerHTML = `${data[i].memory}%`
        }
        total_display = document.getElementById('node_utilization')

        total_display.innerHTML = `CPU: ${total_cpu_utilization}%<br>Memory: ${total_memory_utilization}%`

        setTimeout(get_container_utilization, 5000)
       
    })
}

function demote_node() {
    $.get("/swarman/api/nodes/{{ node.id }}/demote", function(data, status){
        window.location.reload()
    })
}

function promote_node() {
    $.get("/swarman/api/nodes/{{ node.id }}/promote", function(data, status){
        window.location.reload()
    })
}

function update_availability(state) {
    const csrftoken = getCookie('csrftoken')
    console.log(state)
    $.ajax({
        url: "/swarman/api/nodes/{{ node.id }}/update",
        method: "POST",
        dataType: "json",
        data: {
            "Availability" : state
        },
        headers: {"X-CSRFToken": csrftoken },
        success: function(data){
            console.log(data)
            window.location.reload()
        },
        error: function(data){
            console.log('Failed')
            console.log(data.responseJSON)
        }
    });
}

function sync_node() {
    $.get("/swarman/api/nodes/{{ node.id }}/sync", function(data, status){
        window.location.reload()
    })
}
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

window.onload = get_container_utilization()

</script>
{% endblock %}

hana/swarman/templates/swarman/service_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row" style="padding-bottom: 20px">
        <div class='col' style="padding-top: 10px;">
        <a class="btn btn-outline-primary" href="{% url 'swarman:swarm-dashboard' swarm_id %}">Back to Swarm</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
                <div class="col">
                    <h5>{{ service_name|title }} Details</h5>
                        <p>
                            {{ service_status_display }} <br>
                             <!-- Live Data - Get from JS -->
                             {{ running_tasks }} / {{ replicas }}
                        </p>
                        
                        <p>
                            <strong>ID:</strong> {{ service_id }} <br>
                            <strong>Image:</strong> {{ image }} <br>
                            <strong>Ports:</strong> {{ published_port }} / {{ target_port }}  <br>
                        </p>
                        
                </div>
        </div>
        <div class="col-sm-3 text-center">
            <h5>Node Actions</h5>
                <!-- Live Data - Get from JS The Availability Buttons should be populated by Javascript -->
                {% if service_status == "Paused" %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-success" onclick="scale_service(1)">Restart Service</button>
                    </div>
                {% endif %}
                {% if service_status == "Running" or service_status == "Degraded" %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-warning" onclick="scale_service(0)">Pause Service</button>
                    </div>
                {% endif %}
                    <div class="row" style="padding-top: 10px;">
                        <button type="button" class="btn btn-secondary" onclick="openScaleForm()">Scale Service</button>
                    </div>
                    <div class="row" style="padding-top:10px;">
                        <div class="input-group" id="scale_form" style="visibility: hidden;">
                            <span class="input-group-text">Replicas:</span>
                            <input type="number" class="form-control" value="1" min="0" name="replica_count" id="replica_count">
                            <button class="btn btn-outline-secondary" type="button" onclick="scale()">Scale</button>
                        </div>
                    </div>
        </div>
    </div>
</div>

<script language='javascript'>

function scale_service(replicas) {

    const csrftoken = getCookie('csrftoken')
    $.ajax({
        url: "/swarman/api/service/scale",
        method: "POST",
        dataType: "json",
        data: {
            "swarm_id" : {{ swarm_id }},
            "service_id" : "{{ service_id }}",
            "replicas" : replicas
        },
        headers: {"X-CSRFToken": csrftoken },
        success: function(data){
            console.log(data)
            window.location.reload()
        },
        error: function(data){
            console.log('Failed')
            console.log(data.responseJSON)
        }
    });
}

function scale() {
    var replicas = document.getElementById('replica_count').value;
    scale_service(replicas);
}

function openScaleForm() {
    document.getElementById("scale_form").style.visibility = "visible";
}

// Gets value of a cookie for sending POST requests to API
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

</script>
{% endblock %}

hana/swarman/templates/swarman/swarm_dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <h2>{{ swarm.swarm_name }}</h2>
    </div>
    <div class="row">
        <div class="col-md">
            <div class="row">
                <h3>Nodes</h3>
            </div>
            <div class="row">
                {% for node in nodes %}
                    <div class="col text-center">
                        <p><h4><a href="{% url 'swarman:node-detail' node.id %}">{{ node.hostname|title }}</a></h4></p>
                        <p class="{{ node.get_availability }}">{{ node.get_availability|title }}</p>
                        <p>{{ node.role }}</p>
                        <p><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="{% if node.get_status == 'ready' %}green{% else %}red{% endif %}" class="bi bi-circle-fill" viewbox="0 0 10 10"><circle cx="5" cy="5" r="5" /></svg> {{ node.get_status|title }}

                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <h4>Services</h4>
            </div>
            <div class="row">
                {% for service in services %}
                    {% if service == 'ERROR' %}
                        <span style="color: red;">Error Collecting Service List</span>
                    {% else%}
                    <div class="col text-center align-self-center" style="border: solid; margin: 5px;">
                        <h5><a href="{% url 'swarman:service-detail' swarm.id %}?service={{ service.ID }}">{{ service.name|title }}</a></h5>
                        {% if service.desired_tasks == 0 %}
                            <span class="pause"><strong>PAUSED</strong></span> 
                        {% elif 0 < service.replicas and service.replicas < service.desired_tasks %}
                        <span class="degraded"><strong>DEGRADED</strong></span>
                        {% elif service.replicas == 0 and service.desired_tasks > 0 %}
                            <span class="error"><strong>ERROR</strong></span>
                        {% else %}
                            <span class="running"><strong>RUNNING</strong></span>
                        {% endif %}
                        <p>ID: {{ service.ID }}<br>
                        Image: {{ service.image }}<br>
                        Port: {{ service.published_port }} / {{ service.target_port }}<br>
                        Replicas: {{ service.replicas }} / {{ service.desired_tasks }}<br>

                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col-sm">

            <h5>Swarm Stats</h5>
            <p>Health Check: <strong>Coming Soon</strong><br>
            <p>Manager Count: {{ swarm.manager_count }}</p>
            <p>Node Count: {{ swarm.node_count }}</p>
            <p>Services: 
                {% if services.0 == "ERROR" %}
                    <span style="color: red;">{{ services.0 }}</span>
                {% else %}
                {{ services|length }}</p>
                {% endif %}
        </div>
    </div>

{% endblock %}