hana/hana/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from graphene_django.views import GraphQLView



from . import views


schema_view = get_schema_view(
    openapi.Info(
        title="HANA API",
        default_version='v0.1b',
        description="HANA API for monitoring and managing swarms and nodes",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('swarman/', include(('swarman.urls', 'swarman'), namespace='swarman')),
    path('docs/api', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("graphql",csrf_exempt(GraphQLView.as_view(graphiql=True)), name="schema-graphql"),
]

hana/swarman/urls.py
from django.urls import (
    path,
    include,
)

from . import views


urlpatterns = [
    path('dashboard/<int:swarm_id>', views.swarm_dashboard,
         name='swarm-dashboard'),
    path('nodes/<str:node_id>', views.node_detail, name='node-detail'),
    path('new_swarm/', views.AddSwarm.as_view(), name='new-swarm'),
    path('create_swarm/', views.create_swarm, name='create-swarm'),
    path('swarm/<int:swarm_id>/service', views.service_detail, 
        name='service-detail'),
    path('api/', include('swarman.api.urls')),
    

]

hana/templates/_items/footer.html
<footer class="footer mt-auto py-3 bg-dark">
    <div class="container">
        <span class="text-muted">Footer Content Here</span>
    </div>
</footer>

hana/templates/_items/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">HANA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Swarm Manager
                    </a>
                    <ul class="dropdown-menu hana-nav-dropdown" aria-labelledby="navbarDropdown">                    
                        {% for swarm in swarm_list %}
                            <li><a class="dropdown-item hana-nav-item" href="{% url 'swarman:swarm-dashboard' swarm.id %}">{{ swarm.swarm_name }}</a></li>
                        {% endfor %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item hana-nav-item" href="{% url 'swarman:new-swarm' %}">New Swarm</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                     Documentation
                    </a>
                    <ul class="dropdown-menu hana-nav-dropdown" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item hana-nav-item" href="{% url 'schema-swagger-ui' %}" target="_blank">REST Documentation</a></li>
                        <li><a class="dropdown-item hana-nav-item" href="{% url 'schema-graphql' %}" target="_blank">GraphQL Documentation</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>